# Generated by Django 6.0.4 on 2026-04-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_seed_products_and_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mainImage',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main_images/'),
        ),
    ]
